vehicle-parking-app-v1-main/models/user.py
from . import db

class Users(db.Model):
    id=db.Column(db.Integer,primary_key=True)
    email=db.Column(db.String(50),unique=True,nullable=False)
    password=db.Column(db.String(50),nullable=False)
    name=db.Column(db.String(50),nullable=False,default='User')

vehicle-parking-app-v1-main/controllers/user.py
from flask import Blueprint, render_template, request,redirect, session, url_for,flash
from models import db
from models.user import Users
user_bp = Blueprint('user_bp', __name__,)
@user_bp.route('/register', methods=['GET','POST'])
def user_register():
    if request.method=='POST':
        email=request.form.get('email')
        password=request.form.get('password')
        name=request.form.get('name')
        new=Users(email=email,password=password,name=name)
        er = Users.query.filter_by(email=email).first()
        if er:
            print("User already exists, please login")
            return redirect('/user/login')
        db.session.add(new)
        db.session.commit()
        print("User registered successfully,now login")
        return render_template("login.html")
    return render_template("register.html")
@user_bp.route('/login', methods=['GET','POST'])
def user_login():
    if request.method=='POST':
        email=request.form.get('email')
        password=request.form.get('password')
        user=Users.query.filter_by(email=email,password=password).first()
        if user:
            return redirect(url_for('udashboard_bp.profile', user_id=user.id))
        else:
            return render_template("login.html",l=True)
    return render_template("login.html")

vehicle-parking-app-v1-main/templates/add_lot.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Add Parking Lot</title>
    <link rel="stylesheet" href="/static/S3.CSS">
</head>
<body>
    
    <form action="/adashboard/addparkinglot" method="POST">
        <h1><center>Add Parking Lot</center></h1>
        <label for="prime_location">Prime Location:</label>
        <input type="text" id="prime_location" name="prime_location" required><br>

        <label for="price">Price:</label>
        <input type="number" id="price" name="price" required><br>

        <label for="status">Status:</label>
        <input type="number" id="status" name="status" required><br>

        <label for="address">Address:</label>
        <input type="text" id="address" name="address" required><br>

        <label for="pin_code">Pin Code:</label>
        <input type="text" id="pin_code" name="pin_code" required><br>

        <label for="max_slots">Max Slots:</label>
        <input type="number" id="max_slots" name="max_slots" required><br>

        <label for="name">Name:</label>
        <input type="text" id="name" name="name" required><br>
<br>
        <button type="submit">Add parking lot</button>
        <a href="/adashboard/profile" class="btn">Cancel</a>
    </form>
</body>
</html>

vehicle-parking-app-v1-main/templates/admin_dash.html
<!DOCTYPE
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
    <link rel="stylesheet" href="/static/s4.css">
</head>
<body><nav id="a1">
    {% if m %}
    <script>
        alert("Can't Delete Occupied Lot")
    </script>
    {% endif %}
    <div><center><h1>Admin Dashboard</h1></center></div>
    <div id="a2">
        <label><a href="/adashboard/profile">HOME|</a></label>
        <label><a href="/adashboard/users">Users|</a></label>
        <label><a href="/adashboard/Search">Search|</a></label>
        <label><a href="/adashboard/summary">Summary|</a></label>
        <label><a href="/admin/login">Logout|</a></label>
        <label><a href="/adashboard/editprofile">View/Edit Profile|</a></label></nav>
    <h2><center>Parking lots</center></h2>
    
    <center><a id="pl" href="/adashboard/addparkinglot">Add Parking Lot</a></center>
    <div id="main"><div id="lot">
    {% for j in lots %}
    <div class="lot">
    <h3>{{ j.name }}</h3>
    <center>
        <label><a id="ss" href="/adashboard/{{ j.id }}/editlot">Edit</a></label>
        <label><a id='ss'href="/adashboard/{{ j.id }}/remove">Remove</a></label></center>
        <p> price:{{ j.price }}rs/hr</p>
        <div id="slot">
            {% for i in range(1,j.max_slots+1) %}
            {% set spot_id=j.id|string+i|string %}
            {% if not delsp(j.id,i) %}
            {% if not booked(spot_id) %}
        <a href="/adashboard/{{ j.id }}{{ i }}/viewsp"><button style="background-color: red; color: white;">Slot {{ i }}</button></a>
            {% else %}
        <a href="/adashboard/{{ j.id }}{{ i }}/viewsp"><button style="background-color: green; color: white;">Slot {{ i }}</button></a>
            {% endif %}
            {% else %}
        {% endif %}
{% endfor %}

        </div>
        <p >.......................</p>
    </div>
    {% endfor %}
    </div>
    
    
    </nav>
</body>
</html>

vehicle-parking-app-v1-main/templates/adminlogin.html
</html><!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
    <link rel="stylesheet" href="/static/s2.css">
</head>
<body>
    <nav id="abc">
    <div class="form1">
        <h2>Login</h2>
        <form action="/admin/login" method="post">
            <label >Email:</label>
            <input type="email" id="mail" name="email" required>
            <br>
            <label>Password:</label>
            <input type="password" id="password" name="password" required>
            <br>
            <button type="submit">Login</button><br>
            <a href="/user/login">login as user</a>
    </nav>
</body>

vehicle-parking-app-v1-main/templates/book_spot.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
    <link rel="stylesheet" href="/static/S3.CSS">
</head>
<body>
    

    <form action="/udashboard/{{ user.id }}/{{ lot.id }}/bookspot" method="POST">
        <h1><center>Book Parking Spot</center></h1>
        <input type="hidden" name="lot_id" value="{{ lot.id }}">
        <label for="spot_id">spotid:</label>
        <input type="number" id="spot_id" name="spot_id" value="{{ spot_id }}" readonly><br><br>

        <label for="lot_id">lot_id:</label>
        <input type="number" id="lot_id" name="lot_id" value="{{ lot.id }}" readonly><br><br>
        <label for="user_id">User_id:</label>
        <input type="number" id="user_id" name="user_id" value="{{ user.id }}" readonly><br><br>
        <label for="vehicle_number">Vehicle Number:</label>
        <input type="text" id="vehicle_number" name="vehicle_number" required><br><br>
        <label for="start_time">Start Time:</label>
        <input type="datetime-local" id="start_time" name="start_time" required><br><br>
        <label for="end_time">End Time:</label>
        <input type="datetime-local" id="end_time" name="end_time" required><br><br>
        <button type="submit">Reserve</button>
        <a href="/udashboard/{{ user.id }}/profile"><button type="button">Cancel</button></a>
    </form>
</body>
</html>

vehicle-parking-app-v1-main/templates/edit_profile.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Edit Profile</title>
    <link rel="stylesheet" href="/static/S3.CSS">
</head>
<body>
    <center><h1>Edit Profile</h1></center>
    <form action="/adashboard/editprofile" method="post">
        <label for="name">New Name:</label>
        <input type="text" id="name" name="name" required><br><br>
        <label for="password">New Password:</label>
        <input type="password" id="password" name="password" required><br><br>
        <label for="confirm_password">New Confirm Password:</label>
        <input type="password" id="confirm_password" name="confirm_password" required><br><br>
        <button  type="submit">Update</button>
        <a  class="btn" href="/adashboard/profile">Cancel</a>
    </form>
</body>
</html>

vehicle-parking-app-v1-main/templates/err.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Error</title>
</head>
<body>
    <h1>Error</h1>
    <p>lot is full</p>
    <p><a href="/udashboard/{{ user.id }}/profile">Back to Dashboard</a></p>
</body>
</html>

vehicle-parking-app-v1-main/templates/index.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Welcome</title>
    <link rel="stylesheet" href="{{ url_for('static',filename='style.css') }}">
</head>
<body>
    <nav id="head">
    <h1><center><b>Welcome to the Vehicle Parking App</b></center></h1>
    </nav>
    <nav id="head2">
        <h2>choose your role</h2>
    </nav>
    <div id="buttons">
        <form action="{{ url_for('role') }}" method="POST">
        <div class="bdiv">
        <button type="submit" name="role" value="user"><h1>USERS</h1></button>
            </div>
        </form>
    <form action="{{ url_for('role') }}" method="POST">
        <div class="bdiv">
        <button type="submit" name="role" value="admin"><h1>ADMIN</h1></button>
        </div>
        </form>
    </div>
</body>
</html>

vehicle-parking-app-v1-main/templates/login.html
</html><!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
    <link rel="stylesheet" href="/static/s2.css">
</head>
<body>
    {% if l %}
    <script>
        alert("Check your details")
    </script>
    {% endif %}
    <nav id="abc">
    <div class="form1">
        <h2>Login</h2>
        <form action="/user/login" method="post">
            <label >Email:</label>
            <input type="email" id="mail" name="email" required>
            <br>
            <label>Password:</label>
            <input type="password" id="password" name="password" required>
            <br>
            <button type="submit">Login</button><br>
            <a href="{{ url_for('user_bp.user_register') }}">Create new account/register</a>
    </div>
    </nav>
</body>

vehicle-parking-app-v1-main/templates/search_user.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
    <link rel="stylesheet" href="/static/S3.CSS">
</head>
<body><div>
    <div>
    <h2><center>Search</center></h2>
    <form action="/adashboard/Search" method="post">
    <label for="search_type">Search Type:
    <select  id="srch" name="search_type" id="search_type">
    <option value="user_id">user_id</option>
    <option value="ploc">parking lot by location</option>
    </select></label>
    <br><br>
    <input type="text" name="search" placeholder="Enter Here" required>
    <br></br>
    <button type="submit">Search</button>
    </form>
    </div>
    <div>
    <h2><center>Search Results</center></h2>
    {% if search_type == 'user_id' %}
        <h3>User Details</h3>
            <table border="1">
                <tr>
                    <th>User ID</th>
                    <th>Email</th>
                    <th>Vehicle Number</th>
                    <th>Duration</th>
                </tr>
        {% if not users %}
            <tr>
                <td>{{ user.id }}</td>
                <td>{{ user.email }}</td>
                <td>--</td>
                <td>--</td>
            </tr>
        {% endif %}
                {% for u in users %}
                <tr>
                    <td>{{ user.id }}</td>
                    <td>{{ user.email }}</td>
                    <td>{{ u.vehicle_number }}</td>
                    <td>{{ u.start_time }} --- {{ u.end_time }}</td>
                </tr>
                {% endfor %}
            </table>
    {% elif search_type == 'ploc' %}
    <div id="wer"> 
    <h3>Parking Lot Details</h3>
        {% if not lots %}
            <p>No lots found.</p>
        {% else %}
            {% for lot in lots %}
            <div class="lot">
                <h3>{{ lot.name }}</h3>
                <p>Price: {{ lot.price }} Rs/hr</p>
                <div>
                    {% for i in range(1, lot.max_slots + 1) %}
                        <button>Slot {{ i }}</button>
                    {% endfor %}
                </div>
            </div>  
            <p>---------</p>
            {% endfor %}
        {% endif %}
    {% endif %}
    </div>
        </div>
        </div>
        <br>
        <footer>
<a href="/adashboard/profile" class="btn">Back to Dashboard</a><br> </footer>
</body>
</html>

vehicle-parking-app-v1-main/templates/sum.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
    <link rel="stylesheet" href="/static/s9.css">
    <script src="https://cdn.jsdelivr.net/npm/chart.js"></script>
    
</head>
<body>
    <h2>SUMMARY</h2>
    <h3>Frequently Booked LOTS(booked by you)</h3>
    <nav id="hl">
    <canvas id="dl"></canvas>
    </nav><nav id="f1">
    <h3>VEHICLE SUMMARY(vehicles used for booking)</h3>
    <canvas id="ff"></canvas>
    </nav>
    <script id="dd" type="application/json">
        {
            "lab1":{{ l1|tojson}},
            "val1":{{ l2|tojson}},
            "lab2":{{ p1|tojson}},
            "val2":{{ p2|tojson}}
        }
    </script>
    <script>
        const x=document.getElementById("dl").getContext('2d')
        const y=JSON.parse(document.getElementById("dd").textContent);
        new Chart(x,{
            type:"bar",
            data:{labels:y.lab1,
                datasets:[{
                    label:"Top Booked Lots",
                    data:y.val1,
                    borderColor:"rgba(75, 192, 192, 1)",borderWidth:1,
                    backgroundColor:"rgba(75, 192, 192, 0.2)",
                }]
            },
            options:{
                responsive:true,
                plugins:{title:{
                        display:true,
                        text:"Top booked lots"
                    },
                legend:{
                    display:true,
                }
            }
        }
        })
    </script>
    <script>
        const w=document.getElementById("ff").getContext('2d')
        const g=JSON.parse(document.getElementById("dd").textContent);
        const t=g.lab2.length;
        const bg=[];
        const bc=[];
        for(let i=0;i<t;i++){
            const r=Math.round((360/t)*i);
            bg.push(`hsl(${r},70%,70%)`);
            bc.push(`hsl(${r},70%,30%)`);
        }
        new Chart(w,{
            type:"pie",
            data:{
                labels:g.lab2,
                datasets:[{
                    label:"Vechile summary",
                        data:g.val2,
                        backgroundColor:bg,
                        borderColor:bc,
                        borderWidth:1
                    }]
                }
        ,
            options:{
                responsive:true,
                plugins:{title:{
                        display:true,
                        text:"Vechile summary"
                    },
                    legend:{
                        display:true,
                    }
                }
            }
        })
    </script>
</body>
<a id="ok" href="/udashboard/{{ user_id }}/profile">Back to Dashboard</a>
</html>

vehicle-parking-app-v1-main/templates/summ.html
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>Users vs Their Bookings</title>
  <link rel="stylesheet" href="/static/s9.css">
  <script src="https://cdn.jsdelivr.net/npm/chart.js"></script>
</head>
<body>
  <h2>Summary</h2>
  <nav id="hl">
    <h3>Users vs Their Bookings</h3>
  <canvas id="ub"></canvas>
  </nav>
  <h3>Top Demanded Areas</h3>
  <div id="td"><canvas id="ta"></canvas>
  </div>
  </nav>
   <script id="cd" type="application/json">
    {
      "labels1": {{ ul|tojson }},
      "data1": {{ uc|tojson }},
      "labels2": {{ ta|tojson }},
      "data2": {{ tc|tojson }}  
    }
  </script>
  <script>
  const cd = JSON.parse(document.getElementById("cd").textContent);
  const x = document.getElementById("ub").getContext('2d');
  new Chart(x,{
    type:"bar",
    data:{
      labels:cd.labels1,
      datasets: [{label: 'No of bookings',data:cd.data1,
        backgroundColor: 'rgba(54,162,235,0.7)'
      }]
    },
    options:{
      responsive: true,
      plugins:{
        legend:{ display: false },
        title:{
          display:true,
          text:'Users vs Their Bookings'
        }
      }
    }
  });
  const y=document.getElementById("ta").getContext('2d');
new Chart(y,{
  type: "pie",
  data:{
    labels:cd.labels2,
    datasets:[{
      label:'No of bookings',
      data:cd.data2,
      backgroundColor:[
        'rgba(255,99,132,0.7)',
        'rgba(54,162,235,0.7)',
        'rgba(255,206,86,0.7)',
        'rgba(75,192,192,0.7)',
        'rgba(153,102,255,0.7)'
      ]
    }]
  },
  options:{
    responsive:true,
    plugins:{
      legend:{ display: true },
      title:{
        display:true,
        text:'Areas Vs Their Demand'
      }
    }
  }
});

</script>
<footer>
  <a id="ok" href="/adashboard/profile">Back to Dashboard</a>
</footer>
</body>
</html>

vehicle-parking-app-v1-main/templates/users.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
    <link rel="stylesheet" href="/static/s6.css">
</head>
<body>
    <h2 id="er"><center>User List</center></h2>
    <br>
    <table>
        <thead>
            <tr>
                <th>Username</th>
                <th>Email</th>
            </tr>
        </thead>
        <tbody>
            {% for l in users %}
            <tr>
                <td>{{ l.name }}</td>
                <td>{{ l.email }}</td>
            </tr>
            {% endfor %}
        </tbody>
    </table>
    <footer>
    <a id="ll" href="/adashboard/profile" >Back to Dashboard</a></footer>
</body>
</html>

vehicle-parking-app-v1-main/templates/view_profile.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
    <link rel="stylesheet" href="/static/s7.css">
</head>
<body>
    <center><h1>View Profile</h1></center>
    <div id="pp">
    <form action="/adashboard/update" method="post">
    <label for="email">Email: <span>{{ user.email }}</span></label><br><br>
    <label id="po" for="name">Name: <span>{{ user.name }}</span></label><br><br>
    <button type="submit">Update</button>
    <a href="/adashboard/profile" style="display:inline-block; background-color: rgb(34,45,50); color:white; padding:7px; text-decoration:none;">Back</a>
</form>
    </div>
</body>
</html>

vehicle-parking-app-v1-main/templates/viewsp.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
    <link rel="stylesheet" href="/static/S3.CSS">
</head>
<body>
    {% if m %}
        <script>
            alert("Can't Delete Occupied spot")
        </script>
    {% endif %}
    <form action="/adashboard/{{ spot_id }}/spd" method="POST">
    <h2><center>View/Delete spot</center></h2>
    <label for="sp">spot id:</label>
    <input id="sp" name="spot" value="{{ spot_id }}" readonly><br>
    <label>Status:</label>
    <button type="submit" name="status" value="{{ status }}">{{ status }}</button><br>
    <br>
    
    <a href="/adashboard/{{ spot_id }}/{{ status }}/delspot"><button type="button">Delete</button></a>
    <a href="/adashboard/profile"><button type="button">Close</button></a>

    </form>
    
</body>
</html>